### ISSUE TITLE
pkg-config not found on ubuntu when installing flavor ozwdev

### ISSUE THREAD

**Issue by chilicheech** [OpenZWave/python-openzwave#114]
Getting the following error when installing python_openzwave ozwdev flavor with `pip3 install python_openzwave --install-option="--flavor=ozwdev"`. Dependencies were installed according to the readme `pip3 install cython wheel six 'PyDispatcher>=2.0.5'`:
```
Collecting python_openzwave
  Downloading python_openzwave-0.4.1.zip (136kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-u799cuhx/python-openzwave/pyozw_pkgconfig.py", line 59, in _wrapper
        return func(*args, **kwargs)
      File "/tmp/pip-build-u799cuhx/python-openzwave/pyozw_pkgconfig.py", line 86, in exists
        return subprocess.call(cmd) == 0
      File "/usr/lib/python3.6/subprocess.py", line 267, in call
        with Popen(*popenargs, **kwargs) as p:
      File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config': 'pkg-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-build-u799cuhx/python-openzwave/pyozw_setup.py", line 864, in parse_template
        if pyozw_pkgconfig.exists('libopenzwave'):
      File "/tmp/pip-build-u799cuhx/python-openzwave/pyozw_pkgconfig.py", line 61, in _wrapper
        raise EnvironmentError("pkg-config is not installed")
    OSError: pkg-config is not installed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-u799cuhx/python-openzwave/setup.py", line 36, in <module>
        from pyozw_setup import LOCAL_OPENZWAVE, SETUP_DIR
      File "/tmp/pip-build-u799cuhx/python-openzwave/pyozw_setup.py", line 882, in <module>
        current_template = parse_template(sys.argv)
      File "/tmp/pip-build-u799cuhx/python-openzwave/pyozw_setup.py", line 867, in parse_template
        log.exception("Can't use precompiled openzwave library")
    AttributeError: module 'distutils.log' has no attribute 'exception'
```

**Comment by chilicheech** [comment]
I installed pkg-config via `apt-get install pkg-config` and it worked. This was previously working without installing pkg-config for version 0.4.0.35. Maybe we should document somewhere that we also need to install pkg-config beforehand? Maybe it's already documented and I missed it.

Cheers,

**Comment by bibi21000** [comment]
It's a bug
I'll fix it ine the next few days

**Comment by bibi21000** [comment]
Fixed
Thanks

**Comment by chilicheech** [comment]
Thanks for the quick response and for fixing :)
