### ISSUE TITLE
Can't import ZWaveOption

### ISSUE THREAD

**Issue by TXC** [OpenZWave/python-openzwave#12]
As #10 implies the project Home-Assistant is using this project.

When activating zwave module the following error occurs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/bootstrap.py", line 96, in _setup_component
    if not component.setup(hass, config):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/zwave.py", line 67, in setup
    from openzwave.option import ZWaveOption
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 269, in __exit__
  File "<frozen importlib._bootstrap>", line 221, in release
RuntimeError: cannot release un-acquired lock
```

**Comment by stefan-jonasson** [comment]
@TXC It seems like this is the same problem as in #11. Does it work for you if you try that solution?

**Comment by bibi21000** [comment]
There is a problem with the mapping of string in cython, you can look at comment (in french) here : https://github.com/OpenZWave/python-openzwave/commit/530a1cff930d68674af0ce6e2f450dcd98014c5e

**Comment by bibi21000** [comment]
Sould be fixed. Python3 related
