### ISSUE TITLE
undefined symbol: _ZN9OpenZWave7Manager16GetNodeProductIdB5cxx11Ejh

### ISSUE THREAD

**Issue by hats0id** [OpenZWave/python-openzwave#124]
Hi everyone!

Installed homeassistant and have problem with setting up zwave component:

```
Log Details (ERROR)
Mon Jun 18 2018 17:58:41 GMT+0300 (E. Europe Daylight Time)
Error during setup of component zwave
Traceback (most recent call last):
  File "/opt/homeassistant/lib64/python3.5/site-packages/homeassistant/setup.py", line 143, in _async_setup_component
    hass, processed_config)
  File "/opt/homeassistant/lib64/python3.5/site-packages/homeassistant/components/zwave/__init__.py", line 229, in async_setup
    from openzwave.option import ZWaveOption
  File "/root/.homeassistant/deps/lib64/python3.5/site-packages/openzwave/option.py", line 29, in <module>
    import libopenzwave
ImportError: /root/.homeassistant/deps/lib64/python3.5/site-packages/libopenzwave.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN9OpenZWave7Manager16GetNodeProductIdB5cxx11Ejh

```

any ideas what's going wrong?

i have gentoo linux, python 3.5.5, python-openzwave 0.4.4 and ha 0.71

**Comment by hats0id** [comment]
Looks like problem related to HA. Installed python-openzwave from sources and all works fine.
