### ISSUE TITLE
Non-integer value passed to libopenzwave.PyManager.cancelControllerCommand

### ISSUE THREAD

**Issue by cslarsen** [OpenZWave/python-openzwave#15]
Got this while starting and stopping python-openzwave many times. May look into it myself, but seems just to be an invalid binding or value passed to the C++ function.

Traceback (most recent call last):
  File "home.py", line 285, in <module>
    main()
  File "home.py", line 278, in main
    network.stop()
  File "/usr/local/lib/python2.7/dist-packages/openzwave-0.3.0b5-py2.7.egg/openzwave/network.py", line 396, in stop
    self.controller.stop()
  File "/usr/local/lib/python2.7/dist-packages/openzwave-0.3.0b5-py2.7.egg/openzwave/controller.py", line 201, in stop
    self.cancel_command()
  File "/usr/local/lib/python2.7/dist-packages/openzwave-0.3.0b5-py2.7.egg/openzwave/controller.py", line 804, in cancel_command
    return self._network.manager.cancelControllerCommand(self.home_id)
  File "libopenzwave.pyx", line 3765, in libopenzwave.PyManager.cancelControllerCommand (src-lib/libopenzwave/libopenzwave.cpp:200
53)
TypeError: an integer is required

**Comment by bibi21000** [comment]
You can look at tests, the is one which test this.
I'm pretty sure you stop the network before receiving a home_id.
By the way, as said in docs it's a bad idea to stop and restart network. You'd better to create a new network after stopping

**Comment by bibi21000** [comment]
Should be fixed now
