### ISSUE TITLE
UnicodeDecodeError in a logging.debug() call

### ISSUE THREAD

**Issue by AxelVoitier** [OpenZWave/python-openzwave#25]
Hello,

When my network start I get the following errors (with some debug around to put it back in context):

```
DEBUG:libopenzwave:notif_callback : new notification
DEBUG:libopenzwave:notif_callback : Notification (type,nodeId) : (None, 9)
DEBUG:libopenzwave:addValueId : ValueID : 72057594194739225
DEBUG:libopenzwave:addValueId : Notification : {'homeId': 3741043003, 'valueId': {'index': 1, 'units': u'', 'type': 'Raw', 'nodeId': 9, 'value': '\x8f@\n\xad)\x00\x01\x04\x00\x00', 'commandClass': 'COMMAND_CLASS_USER_CODE', 'instance': 1, 'readOnly': False, 'homeId': 3741043003, 'label': u'Code 1:', 'genre': 'User', 'id': 72057594194739225L}, 'notificationType': 'ValueAdded', 'nodeId': 9}
DEBUG:libopenzwave:notif_callback : call callback context
DEBUG:openzwave:zwcallback args=[{'homeId': 3741043003, 'valueId': {'index': 1, 'units': u'', 'type': 'Raw', 'nodeId': 9, 'value': '\x8f@\n\xad)\x00\x01\x04\x00\x00', 'commandClass': 'COMMAND_CLASS_USER_CODE', 'instance': 1, 'readOnly': False, 'homeId': 3741043003, 'label': u'Code 1:', 'genre': 'User', 'id': 72057594194739225L}, 'notificationType': 'ValueAdded', 'nodeId': 9}]
DEBUG:openzwave:Z-Wave Notification ValueAdded : {'homeId': 3741043003, 'valueId': {'index': 1, 'units': u'', 'type': 'Raw', 'nodeId': 9, 'value': '\x8f@\n\xad)\x00\x01\x04\x00\x00', 'commandClass': 'COMMAND_CLASS_USER_CODE', 'instance': 1, 'readOnly': False, 'homeId': 3741043003, 'label': u'Code 1:', 'genre': 'User', 'id': 72057594194739225L}, 'notificationType': 'ValueAdded', 'nodeId': 9}
DEBUG:openzwave:Create object value (valueId:72057594194739225)
ERROR:openzwave:Error in manager callback : ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/pyozwweb-0.3.0b7-py2.7.egg/openzwave/network.py", line 947, in zwcallback\n    self._handle_value_added(args)\n', '  File "/usr/local/lib/python2.7/site-packages/pyozwweb-0.3.0b7-py2.7.egg/openzwave/network.py", line 1478, in _handle_value_added\n    self._handle_value(node=self.nodes[args[\'nodeId\']], value=self.nodes[args[\'nodeId\']].values[args[\'valueId\'][\'id\']])\n', '  File "/usr/local/lib/python2.7/site-packages/pyozwweb-0.3.0b7-py2.7.egg/openzwave/network.py", line 1450, in _handle_value\n    logger.debug(\'Z-Wave Notification Value : node=%s value=%s\' % (node, value))\n', '  File "/usr/local/lib/python2.7/site-packages/pyozwweb-0.3.0b7-py2.7.egg/openzwave/value.py", line 85, in __str__\n    (self._network.home_id_str, self._object_id, self.parent_id, self.label, self.data)\n', "UnicodeDecodeError: 'ascii' codec can't decode byte 0x8f in position 0: ordinal not in range(128)\n"]
DEBUG:libopenzwave:notif_callback : end
DEBUG:libopenzwave:notif_callback : new notification
DEBUG:libopenzwave:notif_callback : Notification (type,nodeId) : (None, 9)
DEBUG:libopenzwave:addValueId : ValueID : 72057594194739241
DEBUG:libopenzwave:addValueId : Notification : {'homeId': 3741043003, 'valueId': {'index': 2, 'units': u'', 'type': 'Raw', 'nodeId': 9, 'value': '\x8f9^T*\x00\x01\x04\x00\x00', 'commandClass': 'COMMAND_CLASS_USER_CODE', 'instance': 1, 'readOnly': False, 'homeId': 3741043003, 'label': u'Code 2:', 'genre': 'User', 'id': 72057594194739241L}, 'notificationType': 'ValueAdded', 'nodeId': 9}
DEBUG:libopenzwave:notif_callback : call callback context
DEBUG:openzwave:zwcallback args=[{'homeId': 3741043003, 'valueId': {'index': 2, 'units': u'', 'type': 'Raw', 'nodeId': 9, 'value': '\x8f9^T*\x00\x01\x04\x00\x00', 'commandClass': 'COMMAND_CLASS_USER_CODE', 'instance': 1, 'readOnly': False, 'homeId': 3741043003, 'label': u'Code 2:', 'genre': 'User', 'id': 72057594194739241L}, 'notificationType': 'ValueAdded', 'nodeId': 9}]
DEBUG:openzwave:Z-Wave Notification ValueAdded : {'homeId': 3741043003, 'valueId': {'index': 2, 'units': u'', 'type': 'Raw', 'nodeId': 9, 'value': '\x8f9^T*\x00\x01\x04\x00\x00', 'commandClass': 'COMMAND_CLASS_USER_CODE', 'instance': 1, 'readOnly': False, 'homeId': 3741043003, 'label': u'Code 2:', 'genre': 'User', 'id': 72057594194739241L}, 'notificationType': 'ValueAdded', 'nodeId': 9}
DEBUG:openzwave:Create object value (valueId:72057594194739241)
ERROR:openzwave:Error in manager callback : ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/pyozwweb-0.3.0b7-py2.7.egg/openzwave/network.py", line 947, in zwcallback\n    self._handle_value_added(args)\n', '  File "/usr/local/lib/python2.7/site-packages/pyozwweb-0.3.0b7-py2.7.egg/openzwave/network.py", line 1478, in _handle_value_added\n    self._handle_value(node=self.nodes[args[\'nodeId\']], value=self.nodes[args[\'nodeId\']].values[args[\'valueId\'][\'id\']])\n', '  File "/usr/local/lib/python2.7/site-packages/pyozwweb-0.3.0b7-py2.7.egg/openzwave/network.py", line 1450, in _handle_value\n    logger.debug(\'Z-Wave Notification Value : node=%s value=%s\' % (node, value))\n', '  File "/usr/local/lib/python2.7/site-packages/pyozwweb-0.3.0b7-py2.7.egg/openzwave/value.py", line 85, in __str__\n    (self._network.home_id_str, self._object_id, self.parent_id, self.label, self.data)\n', "UnicodeDecodeError: 'ascii' codec can't decode byte 0x8f in position 0: ordinal not in range(128)\n"]
DEBUG:libopenzwave:notif_callback : end
DEBUG:libopenzwave:notif_callback : new notification
DEBUG:libopenzwave:notif_callback : Notification (type,nodeId) : (None, 9)
DEBUG:libopenzwave:addValueId : ValueID : 72057594194739257
DEBUG:libopenzwave:addValueId : Notification : {'homeId': 3741043003, 'valueId': {'index': 3, 'units': u'', 'type': 'Raw', 'nodeId': 9, 'value': '\x8f\xc86\xad)\x00\x01\x04\x00\x00', 'commandClass': 'COMMAND_CLASS_USER_CODE', 'instance': 1, 'readOnly': False, 'homeId': 3741043003, 'label': u'Code 3:', 'genre': 'User', 'id': 72057594194739257L}, 'notificationType': 'ValueAdded', 'nodeId': 9}
DEBUG:libopenzwave:notif_callback : call callback context
DEBUG:openzwave:zwcallback args=[{'homeId': 3741043003, 'valueId': {'index': 3, 'units': u'', 'type': 'Raw', 'nodeId': 9, 'value': '\x8f\xc86\xad)\x00\x01\x04\x00\x00', 'commandClass': 'COMMAND_CLASS_USER_CODE', 'instance': 1, 'readOnly': False, 'homeId': 3741043003, 'label': u'Code 3:', 'genre': 'User', 'id': 72057594194739257L}, 'notificationType': 'ValueAdded', 'nodeId': 9}]
DEBUG:openzwave:Z-Wave Notification ValueAdded : {'homeId': 3741043003, 'valueId': {'index': 3, 'units': u'', 'type': 'Raw', 'nodeId': 9, 'value': '\x8f\xc86\xad)\x00\x01\x04\x00\x00', 'commandClass': 'COMMAND_CLASS_USER_CODE', 'instance': 1, 'readOnly': False, 'homeId': 3741043003, 'label': u'Code 3:', 'genre': 'User', 'id': 72057594194739257L}, 'notificationType': 'ValueAdded', 'nodeId': 9}
DEBUG:openzwave:Create object value (valueId:72057594194739257)
ERROR:openzwave:Error in manager callback : ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/pyozwweb-0.3.0b7-py2.7.egg/openzwave/network.py", line 947, in zwcallback\n    self._handle_value_added(args)\n', '  File "/usr/local/lib/python2.7/site-packages/pyozwweb-0.3.0b7-py2.7.egg/openzwave/network.py", line 1478, in _handle_value_added\n    self._handle_value(node=self.nodes[args[\'nodeId\']], value=self.nodes[args[\'nodeId\']].values[args[\'valueId\'][\'id\']])\n', '  File "/usr/local/lib/python2.7/site-packages/pyozwweb-0.3.0b7-py2.7.egg/openzwave/network.py", line 1450, in _handle_value\n    logger.debug(\'Z-Wave Notification Value : node=%s value=%s\' % (node, value))\n', '  File "/usr/local/lib/python2.7/site-packages/pyozwweb-0.3.0b7-py2.7.egg/openzwave/value.py", line 85, in __str__\n    (self._network.home_id_str, self._object_id, self.parent_id, self.label, self.data)\n', "UnicodeDecodeError: 'ascii' codec can't decode byte 0x8f in position 0: ordinal not in range(128)\n"]
DEBUG:libopenzwave:notif_callback : end
```

It seems that when it init the values from my rfid keypad, it comes to read the user code which are actually the tag ids stored as raw byte. That seems to trip off one of the logging.debug() call.
Unfortunately, it could be that it stops the processing of the notification here and does not forward it to the application ;(.

Cheers,
Axel

**Comment by bibi21000** [comment]
Hi
There was some updates for unicode in the last commits. Maybe you can try again.
HTH

**Comment by bibi21000** [comment]
Sould be fixed.
