### ISSUE TITLE
Exception KeyError in 'libopenzwave.notif_callback' ignored

### ISSUE THREAD

**Issue by nechry** [OpenZWave/python-openzwave#44]
with all device support COMMAND_CLASS_CENTRAL_SCENE, during the discovering I got a error:
Exception KeyError: (91,) in 'libopenzwave.notif_callback' ignored

20-04-2016 23:16:59 | debug | value_added. 223 Basic
Exception KeyError: (91,) in 'libopenzwave.notif_callback' ignored
20-04-2016 23:16:59 | debug | value_added. 223 ZWave+ Version
20-04-2016 23:16:59 | debug | value_added. 223 InstallerIcon
20-04-2016 23:16:59 | debug | value_added. 223 UserIcon

if I check the xml 

```
<CommandClass id="32" name="COMMAND_CLASS_BASIC" version="1" request_flags="4">
                <Instance index="1" />
                <Value type="byte" genre="basic" instance="1" index="0" label="Basic" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="255" value="0" />
            </CommandClass>
            <CommandClass id="86" name="COMMAND_CLASS_CRC_16_ENCAP" version="1" request_flags="4" innif="true">
                <Instance index="1" />
            </CommandClass>
            <CommandClass id="90" name="COMMAND_CLASS_DEVICE_RESET_LOCALLY" version="1" request_flags="4" innif="true">
                <Instance index="1" />
            </CommandClass>
            <CommandClass id="91" name="COMMAND_CLASS_CENTRAL_SCENE" version="1" request_flags="4" innif="true" scenecount="0">
                <Instance index="1" />
                <Value type="int" genre="system" instance="1" index="0" label="Scene Count" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="-2147483648" max="2147483647" value="0" />
            </CommandClass>
            <CommandClass id="94" name="COMMAND_CLASS_ZWAVE_PLUS_INFO" version="1" request_flags="4" innif="true">
                <Instance index="1" />
                <Value type="byte" genre="system" instance="1" index="0" label="ZWave+ Version" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="255" value="1" />
                <Value type="short" genre="system" instance="1" index="1" label="InstallerIcon" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="-32768" max="32767" value="5632" />
                <Value type="short" genre="system" instance="1" index="2" label="UserIcon" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="-32768" max="32767" value="5632" />
            </CommandClass>
```

the error occurs with CC COMMAND_CLASS_CENTRAL_SCENE for value Scene Count.

I will also continue to investigate from my side and or propose a patch

**Comment by bibi21000** [comment]
Where does this log come : can't find it in source

**Comment by nechry** [comment]
Hi, I got there king of exception ( 'libopenzwave.notif_callback' ignored) with any error in a notification handler. the Exception KeyError: (91,)  is the real error in python side.

it's easy to raise this kind of errors. just to get this kind of exception add a division by zero here:
https://github.com/OpenZWave/python-openzwave/blob/master/src-lib/libopenzwave/libopenzwave.pyx#L474

**Comment by bibi21000** [comment]
The simplest way to raise an exception is surely raise ;)
But it will not help for your case.

python-openzwave use standard python logging facilities. They were removed in the past, but I reintoduced them a year ago.
When debugging the last commits, here is the output  i've get : 

```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/python-openzwave/tests/api/test_controller_command.py", line 173, in test_025_command_request_node_neighbor_update_controller
    self.assertEqual(current, self.network.controller.STATE_COMPLETED)
AssertionError: 'Failed' != 'Completed'
-------------------- >> begin captured logging << --------------------
openzwave: DEBUG: Send controller command : request_node_neighbor_update, : node : 1
libopenzwave: DEBUG: notif_callback : new notification
libopenzwave: DEBUG: notif_callback : Notification (type,nodeId) : (None, 0)
libopenzwave: DEBUG: notif_callback : call callback context
openzwave: DEBUG: zwcallback args=[{'controllerState': 'Starting', 'controllerError': 'None', 'controllerErrorInt': 0, 'notificationType': 'ControllerCommand', 'nodeId': 0, 'controllerStateInt': 1, 'controllerErrorDoc': 'None.', 'homeId': 21827317, 'controllerStateDoc': 'The command is starting.'}]
openzwave: DEBUG: Z-Wave ControllerCommand : {'controllerState': 'Starting', 'controllerError': 'None', 'controllerErrorInt': 0, 'notificationType': 'ControllerCommand', 'nodeId': 0, 'controllerStateInt': 1, 'controllerErrorDoc': 'None.', 'homeId': 21827317, 'controllerStateDoc': 'The command is starting.'}
libopenzwave: DEBUG: notif_callback : end
libopenzwave: DEBUG: notif_callback : new notification
libopenzwave: DEBUG: notif_callback : Notification (type,nodeId) : (None, 0)
libopenzwave: DEBUG: notif_callback : call callback context
openzwave: DEBUG: zwcallback args=[{'controllerState': 'InProgress', 'controllerError': 'None', 'controllerErrorInt': 0, 'notificationType': 'ControllerCommand', 'nodeId': 0, 'controllerStateInt': 6, 'controllerErrorDoc': 'None.', 'homeId': 21827317, 'controllerStateDoc': 'The controller is communicating with the other device to carry out the command.'}]
openzwave: DEBUG: Z-Wave ControllerCommand : {'controllerState': 'InProgress', 'controllerError': 'None', 'controllerErrorInt': 0, 'notificationType': 'ControllerCommand', 'nodeId': 0, 'controllerStateInt': 6, 'controllerErrorDoc': 'None.', 'homeId': 21827317, 'controllerStateDoc': 'The controller is communicating with the other device to carry out the command.'}
libopenzwave: DEBUG: notif_callback : end
libopenzwave: DEBUG: notif_callback : new notification
libopenzwave: DEBUG: notif_callback : Notification (type,nodeId) : (None, 3)
libopenzwave: DEBUG: addValueId : ValueID : 72057594093273600
libopenzwave: DEBUG: addValueId : Notification : {'homeId': 21827317, 'valueId': {'index': 32, 'units': u'', 'type': 'Bool', 'nodeId': 3, 'value': False, 'commandClass': 'COMMAND_CLASS_METER', 'instance': 1, 'readOnly': True, 'homeId': 21827317, 'label': u'Exporting', 'genre': 'User', 'id': 72057594093273600L}, 'notificationType': 'ValueChanged', 'nodeId': 3}
libopenzwave: DEBUG: notif_callback : call callback context
openzwave: DEBUG: zwcallback args=[{'homeId': 21827317, 'valueId': {'index': 32, 'units': u'', 'type': 'Bool', 'nodeId': 3, 'value': False, 'commandClass': 'COMMAND_CLASS_METER', 'instance': 1, 'readOnly': True, 'homeId': 21827317, 'label': u'Exporting', 'genre': 'User', 'id': 72057594093273600L}, 'notificationType': 'ValueChanged', 'nodeId': 3}]
openzwave: DEBUG: Z-Wave Notification ValueChanged : {'homeId': 21827317, 'valueId': {'index': 32, 'units': u'', 'type': 'Bool', 'nodeId': 3, 'value': False, 'commandClass': 'COMMAND_CLASS_METER', 'instance': 1, 'readOnly': True, 'homeId': 21827317, 'label': u'Exporting', 'genre': 'User', 'id': 72057594093273600L}, 'notificationType': 'ValueChanged', 'nodeId': 3}
libopenzwave: DEBUG: notif_callback : end
libopenzwave: DEBUG: notif_callback : new notification
libopenzwave: DEBUG: notif_callback : Notification (type,nodeId) : (None, 3)
libopenzwave: DEBUG: addValueId : ValueID : 72057594093273218
libopenzwave: DEBUG: addValueId : Notification : {'homeId': 21827317, 'valueId': {'index': 8, 'units': u'W', 'type': 'Decimal', 'nodeId': 3, 'value': 0.0, 'commandClass': 'COMMAND_CLASS_METER', 'instance': 1, 'readOnly': True, 'homeId': 21827317, 'label': u'Power', 'genre': 'User', 'id': 72057594093273218L}, 'notificationType': 'ValueChanged', 'nodeId': 3}
libopenzwave: DEBUG: notif_callback : call callback context
openzwave: DEBUG: zwcallback args=[{'homeId': 21827317, 'valueId': {'index': 8, 'units': u'W', 'type': 'Decimal', 'nodeId': 3, 'value': 0.0, 'commandClass': 'COMMAND_CLASS_METER', 'instance': 1, 'readOnly': True, 'homeId': 21827317, 'label': u'Power', 'genre': 'User', 'id': 72057594093273218L}, 'notificationType': 'ValueChanged', 'nodeId': 3}]
openzwave: DEBUG: Z-Wave Notification ValueChanged : {'homeId': 21827317, 'valueId': {'index': 8, 'units': u'W', 'type': 'Decimal', 'nodeId': 3, 'value': 0.0, 'commandClass': 'COMMAND_CLASS_METER', 'instance': 1, 'readOnly': True, 'homeId': 21827317, 'label': u'Power', 'genre': 'User', 'id': 72057594093273218L}, 'notificationType': 'ValueChanged', 'nodeId': 3}
libopenzwave: DEBUG: notif_callback : end
libopenzwave: DEBUG: notif_callback : new notification
libopenzwave: DEBUG: notif_callback : Notification (type,nodeId) : (None, 0)
libopenzwave: DEBUG: notif_callback : call callback context
openzwave: DEBUG: zwcallback args=[{'controllerState': 'Failed', 'controllerError': 'None', 'controllerErrorInt': 0, 'notificationType': 'ControllerCommand', 'nodeId': 0, 'controllerStateInt': 8, 'controllerErrorDoc': 'None.', 'homeId': 21827317, 'controllerStateDoc': 'The command has failed.'}]
openzwave: DEBUG: Z-Wave ControllerCommand : {'controllerState': 'Failed', 'controllerError': 'None', 'controllerErrorInt': 0, 'notificationType': 'ControllerCommand', 'nodeId': 0, 'controllerStateInt': 8, 'controllerErrorDoc': 'None.', 'homeId': 21827317, 'controllerStateDoc': 'The command has failed.'}
libopenzwave: DEBUG: notif_callback : end
--------------------- >> end captured logging << ---------------------

```

I will try to catch more log in next release, but if you don't use it ;)

**Comment by nechry** [comment]
I add a try except
is the traceback

Traceback (most recent call last):
File "libopenzwave.pyx", line 509, in libopenzwave.notif_callback (src-lib/libopenzwave/libopenzwave.cpp:5724)
File "libopenzwave.pyx", line 456, in libopenzwave.addValueId (src-lib/libopenzwave/libopenzwave.cpp:4981)
KeyError: 91

**Comment by nechry** [comment]
thank
