### ISSUE TITLE
Error in manager callback: KeyError: 'valueId'

### ISSUE THREAD

**Issue by nechry** [OpenZWave/python-openzwave#55]
I got from time to time a error in manager callback:

`[2016-09-27 01:31:34][ERROR] : Error in manager callback
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/openzwave-0.3.0-py2.7.egg/openzwave/network.py", line 948, in zwcallback
self._handle_value_added(args)
File "/usr/local/lib/python2.7/dist-packages/openzwave-0.3.0-py2.7.egg/openzwave/network.py", line 1473, in _handle_value_added
self.nodes[args['nodeId']].add_value(args['valueId']['id'])
KeyError: 'valueId'`

I did not identify on what device and or value this error occur.

I think a possibility to avoid this, is to check if the key exist in args. Or do you think is something I must address to the library openzwave directly, we suppose to receive all arguments ?

**Comment by bibi21000** [comment]
Use logging (as said in your previous issue) to identify node (and more) which causes the error.
If you receive a value_added notification with no value_id, it's not a good idea to 'hide' the problem in the lib. It's normal to raise an exception with no side effects no ?
It's surely a misconfigured node or bugged device.
At first identify the node, check your device config (xml) and after address to the library openzwave

**Comment by nechry** [comment]
I will try to find the device and exactly on what notification and value this exception occur. 

I will return after I will discover where and why. 

thank's

**Comment by philk** [comment]
Not sure if this is helpful but I wasn't getting this error until I grabbed the [CentralScene](https://github.com/jeedom/plugin-openzwave/blob/beta/resources/python-openzwave/openzwave/cpp/src/command_classes/CentralScene.cpp) WIP you'd linked from OpenZWave/open-zwave#993 (which seems to be working great on the openzwave side)

Note that this is inside home-assistant, I could probably get you a stack trace from running python-openzwave directly if it would be helpful.
```
ERROR:openzwave:Error in manager callback
Traceback (most recent call last):
File "/home/pi/hass/venv/lib/python3.4/site-packages/openzwave-0.3.1-py3.4.egg/openzwave/network.py"

self._handle_value_changed(args)
File "/home/pi/hass/venv/lib/python3.4/site-packages/openzwave-0.3.1-py3.4.egg/openzwave/network.py"

'value' : self.nodes[args['nodeId']].values[args['valueId']['id']]})
KeyError: 72057594345603107
ERROR:openzwave:Error in manager callback
Traceback (most recent call last):
File "/home/pi/hass/venv/lib/python3.4/site-packages/openzwave-0.3.1-py3.4.egg/openzwave/network.py"

self._handle_value_changed(args)
File "/home/pi/hass/venv/lib/python3.4/site-packages/openzwave-0.3.1-py3.4.egg/openzwave/network.py"

'value' : self.nodes[args['nodeId']].values[args['valueId']['id']]})
KeyError: 72057594345603107
```
