### ISSUE TITLE
cannot import name 'PyLogLevels'

### ISSUE THREAD

**Issue by garrettpatterson** [OpenZWave/python-openzwave#63]
Running HA on Windows 7 x64, python 3.5.2.  Set up my dev envionment.

Successfully built openzwave and the python wrapper.

HA config:
`zwave:
  usb_path: COM4
  config_path: C:\Users\Garrett\Documents\open-zwave\config`

Error in log when starting HA:
`17-01-13 13:40:50 homeassistant.bootstrap: Error during setup of component zwave
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\homeassistant\bootstrap.py", line 151, in _async_setup_component
    None, component.setup, hass, config)
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 296, in _wakeup
    future.result()
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Program Files (x86)\Python35-32\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\homeassistant\components\zwave\__init__.py", line 256, in setup
    from openzwave.option import ZWaveOption
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\openzwave-0.3.1-py3.5.egg\openzwave\option.py", line 30, in <module>
    from libopenzwave import PyLogLevels
ImportError: cannot import name 'PyLogLevels'`

anyone seen this or have any thoughts?

**Comment by bibi21000** [comment]
What is the result of : 
`
python -c "import libopenzwave; print libopenzwave.__version__"
`

**Comment by garrettpatterson** [comment]
Had to add parentheses around print for python 3, I get:
`module 'libopenzwave' has no attribute __version__'`

Tried just .version also, when I print just 'libopenzwave' it prints the library path which indicates 0.3.2

Just updated to 0.3.2, same results.

**Comment by bibi21000** [comment]
Hi, I've updated the process for windows installation
Could you test : https://github.com/OpenZWave/python-openzwave/blob/master/docs/INSTALL_WIN.rst
