### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by linuxlurak** [OpenZWave/python-openzwave#70]
**libopenzwave**
_apt-cache show libopenzwave1.3_
```
Package: libopenzwave1.3
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 2295
Maintainer: Lucas Nussbaum <lucas@debian.org>
Architecture: armhf
Source: openzwave
Version: 1.4.164
Depends: libc6 (>= 2.13-28), libgcc1 (>= 1:4.4.0), libstdc++6 (>= 4.6), libudev0 (>= 0.140)
Pre-Depends: multiarch-support
Conffiles:
```

**Hardware**
Raspberry Pi 2

**System**
Linux homeautomation 4.4.50+ #970 Mon Feb 20 19:12:50 GMT 2017 armv6l GNU/Linux
Using Home Assistant: 0.39.3

**Python release (python3 --version):**
Python 3.4.2

**Component/platform:**
z-wave

Description of problem:
openzwave throws error "RuntimeError: dictionary changed size during iteration" on startup:

```
17-03-05 19:47:03 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform zwave
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity_component.py", line 151, in _async_setup_platform
    entity_platform.add_entities, discovery_info
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/sensor/zwave.py", line 47, in setup_platform
    add_devices([ZWaveAlarmSensor(value)])
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/sensor/zwave.py", line 55, in __init__
    zwave.ZWaveDeviceEntity.__init__(self, value, DOMAIN)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/zwave/__init__.py", line 681, in __init__
    self._update_attributes()
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/zwave/__init__.py", line 712, in _update_attributes
    label=['Power'])
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/zwave/__init__.py", line 763, in get_value
    return self._value_handler(method='get', **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/zwave/__init__.py", line 731, in _value_handler
    class_id=cid, **kwargs).values())
  File "/usr/local/lib/python3.4/dist-packages/openzwave-0.3.1-py3.4.egg/openzwave/node.py", line 440, in get_values
    for value in self.values:
RuntimeError: dictionary changed size during iteration
```

**Expected:**
Some Error handling / suppression.

**Additional info**
Same problem mentioned here:
https://github.com/home-assistant/home-assistant/issues/1872
https://github.com/home-assistant/home-assistant/issues/6406

**Comment by bibi21000** [comment]
This exception should be fixed.
But keep in mind it's ALWAYS a bad idea to get values before node is_ready (or at least is_info_received).
It will result in missing values or unsupported ones
