### ISSUE TITLE
0.4.0.x Install issue on FreeBSD

### ISSUE THREAD

**Issue by hoopty** [OpenZWave/python-openzwave#74]
System OS details:
```
hass@hass ~ [hass] $uname -a
FreeBSD hass.local 11.0-RELEASE-p9 FreeBSD 11.0-RELEASE-p9 #0: Tue Apr 11 08:48:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

Python info:
```
Python 3.5.3 (default, Apr 15 2017, 08:03:17) 
[GCC 4.2.1 Compatible FreeBSD Clang 3.8.0 (tags/RELEASE_380/final 262564)] on freebsd11
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print (sys.platform);
freebsd11
```

Error:
```
hass@hass ~ [hass] $pip3 install python_openzwave
Collecting python_openzwave
  Downloading python_openzwave-0.4.0.29.zip (133kB)
    100% |################################| 143kB 4.6MB/s 
    Complete output from command python setup.py egg_info:
    ImportError in : from wheel.bdist_wheel import bdist_wheel as _bdist_wheel
    NameError in : class bdist_wheel(_bdist_wheel) - Use bdist_egg instead
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9mb46u89/python-openzwave/setup.py", line 43, in <module>
        print(current_template.ctx)
      File "/tmp/pip-build-9mb46u89/python-openzwave/pyozw_setup.py", line 196, in ctx
        self._ctx = self.get_context()
      File "/tmp/pip-build-9mb46u89/python-openzwave/pyozw_setup.py", line 673, in get_context
        ctx = system_context(ctx, openzwave=self.openzwave, static=True)
      File "/tmp/pip-build-9mb46u89/python-openzwave/pyozw_setup.py", line 178, in system_context
        raise RuntimeError("Can't detect plateform")
    RuntimeError: Can't detect plateform
    <pyozw_setup.EmbedTemplate object at 0x8061596a0>
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9mb46u89/python-openzwave/
```

**Comment by bibi21000** [comment]
Could you test the 0.4.0.30 ?

**Comment by hoopty** [comment]
Better, but still has errors, but the issue now appears to be in the libopenzwave, not particularly the python build.  In case it is related, keep in mind that FreeBSD's native ```make``` is not apporiate and ```gmake``` is what's used.

Here's a build log for reference:
https://gist.github.com/hoopty/901b4f7335739448808b6a839134aee3

**Comment by hoopty** [comment]
OK, I changed my pyozw_setup.py to execute gmake instead of make and I removed 'resolv' from the freebsd definition of ctx['libraries'] and the build works.  PR incoming...

**Comment by bibi21000** [comment]
I've applied your PR in 0.4.0.31.
Could you try it  and update your post in https://github.com/OpenZWave/python-openzwave/issues/73
TIA

**Comment by hoopty** [comment]
It built & installed properly, closing.  Thanks!
