### ISSUE TITLE
Error with pyozw_shell on FreeBSD

### ISSUE THREAD

**Issue by hoopty** [OpenZWave/python-openzwave#76]
When running the ozw manager, I get the following (on Python 3.5.3):

```
 $pyozw_shell -d /dev/cuaU0 -l    
Traceback (most recent call last):
  File "/home/hass/hass/bin/pyozw_shell", line 4, in <module>
    __import__('pkg_resources').run_script('pyozwman==0.4.0.31', 'pyozw_shell')
  File "/home/hass/hass/lib/python3.5/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/hass/hass/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1497, in run_script
    source = open(script_filename).read()
  File "/usr/local/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 280: ordinal not in range(128)
```

**Comment by hoopty** [comment]
Figured it out, thanks!
