### ISSUE TITLE
segfault when handling color message

### ISSUE THREAD

**Issue by robbiet480** [OpenZWave/python-openzwave#79]
Got this when playing around with Z-Wave color tonight in Home Assistant.

```
Thread 37 "python3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff837fe700 (LWP 15676)]
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:169
169     ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) backtrace
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:169
#1  0x00007fffae5cb3c2 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007fffae9676ef in OpenZWave::Color::HandleMsg(unsigned char const*, unsigned int, unsigned int) ()
   from /home/robbiet480/home-assistant/venv/lib/python3.5/site-packages/libopenzwave-0.3.2-py3.5-linux-x86_64.egg/libopenzwave.cpython-35m-x86_64-linux-gnu.so
#3  0x00007fffae93d6d2 in OpenZWave::Node::ApplicationCommandHandler(unsigned char const*, bool) ()
   from /home/robbiet480/home-assistant/venv/lib/python3.5/site-packages/libopenzwave-0.3.2-py3.5-linux-x86_64.egg/libopenzwave.cpython-35m-x86_64-linux-gnu.so
#4  0x00007fffae9383d9 in OpenZWave::Driver::ProcessMsg(unsigned char*) ()
   from /home/robbiet480/home-assistant/venv/lib/python3.5/site-packages/libopenzwave-0.3.2-py3.5-linux-x86_64.egg/libopenzwave.cpython-35m-x86_64-linux-gnu.so
#5  0x00007fffae938f9d in OpenZWave::Driver::ReadMsg() ()
   from /home/robbiet480/home-assistant/venv/lib/python3.5/site-packages/libopenzwave-0.3.2-py3.5-linux-x86_64.egg/libopenzwave.cpython-35m-x86_64-linux-gnu.so
#6  0x00007fffae93934a in OpenZWave::Driver::DriverThreadProc(OpenZWave::Event*) ()
   from /home/robbiet480/home-assistant/venv/lib/python3.5/site-packages/libopenzwave-0.3.2-py3.5-linux-x86_64.egg/libopenzwave.cpython-35m-x86_64-linux-gnu.so
#7  0x00007fffae97fd13 in OpenZWave::ThreadImpl::Run() ()
   from /home/robbiet480/home-assistant/venv/lib/python3.5/site-packages/libopenzwave-0.3.2-py3.5-linux-x86_64.egg/libopenzwave.cpython-35m-x86_64-linux-gnu.so
#8  0x00007fffae97fd29 in OpenZWave::ThreadImpl::ThreadProc(void*) ()
   from /home/robbiet480/home-assistant/venv/lib/python3.5/site-packages/libopenzwave-0.3.2-py3.5-linux-x86_64.egg/libopenzwave.cpython-35m-x86_64-linux-gnu.so
#9  0x00007ffff7bc16ba in start_thread (arg=0x7fff837fe700) at pthread_create.c:333
#10 0x00007ffff78f782d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by bibi21000** [comment]
Is the node in ready state when you try to launch that command ?

**Comment by robbiet480** [comment]
I believe it is but am about to retest it and will report back.

**Comment by bibi21000** [comment]
timeout
