### ISSUE TITLE
SystemError: error return without exception set

### ISSUE THREAD

**Issue by kdschlosser** [OpenZWave/python-openzwave#99]
OK this is the setup..
Windows 7 x64 SP1
Python 2.7.9 32 bit

I have managed to get python-openzwave to build but now I am faced with this traceback when i import openzwave. if i am not mistaken i think the libopenzwave.cpp file is automatically generated by cython. now i am not sure why there is an error there. so i figured maybe someone could shed a little light on it.

    Traceback (most recent call last):
      File "C:/Users/Administrator/Desktop/New folder (21)/test.py", line 1, in <module>
        from openzwave import controller
      File "C:\Python27\lib\site-packages\openzwave\controller.py", line 34, in <module>
        from libopenzwave import PyStatDriver, PyControllerState
      File "src-lib/libopenzwave/libopenzwave.pyx", line 73, in init libopenzwave (openzwave-embed/open-zwave-master/python-openzwave/src-lib/libopenzwave/libopenzwave.cpp:39883)
      File "C:\Python27\lib\logging\__init__.py", line 1298, in addHandler
        def addHandler(self, hdlr):
    SystemError: error return without exception set

**Comment by bibi21000** [comment]
Hi, I've updated the process for windows installation
Could you test : https://github.com/OpenZWave/python-openzwave/blob/master/docs/INSTALL_WIN.rst

**Comment by kdschlosser** [comment]
I forgot about this. 

This issue was actually caused by stackless python and Cython bumping heads. Cython uses PyEval and stackless was not set up in a manner to have this directly accessed.

This issue was actually fixed only recently within the last 30 days. Took a year to find the cause of the problem. LOL
